app = "gren-packages"
kill_signal = "SIGINT"
kill_timeout = 10
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  GREN_PORT = "8080"
  GREN_CANONICAL_URL = "https://packages.gren-lang.org"
  GREN_PACKAGES_DATABASE = "/data/db.sqlite"
  GREN_ZULIP_USERNAME = "packages-bot@gren.zulipchat.com"
  GREN_ZULIP_REALM = "https://gren.zulipchat.com"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source = "gren_packages_data"
  destination = "/data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.http_checks]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 1000
    tls_skip_verify = false
